---
title: "Epigenetic Control of Temperature Response in Ostreococcus tauri (ECTOR)"
author: "Christina Arvanitidou"
date: "2023-05-02"
output: pdf_document
---

## Loading data and preprocessing

```{r}

library(ChIPseeker)
library(TxDb.Otauri.JGI)
txdb <- TxDb.Otauri.JGI


## Crear y leer fichero de picos

peaks.k27.consensus <- readPeakFile(peakfile = "chipseq_data/bed_data/h3k27me3/h3k27me3_consensus.bed",header=FALSE)



## Definir la región que se considera promotor entorno al TSS
promoter <- getPromoters(TxDb=txdb, 
                         upstream=1000, 
                         downstream=1000)


## Anotación de los picos
k27.consensus.peakAnno <- annotatePeak(peak = peaks.k27.consensus, 
                             tssRegion=c(-1000, 1000),
                             TxDb=txdb)


```

```{r}

## Convertir la anotación a data frame

is.data.frame(k27.consensus.peakAnno)

k27.consensus.annotation <- as.data.frame(k27.consensus.peakAnno)
head(k27.consensus.annotation)

#Guardar los genes dianas de k27 en LD 
target.genes.k27.consensus <-k27.consensus.annotation$geneId[k27.consensus.annotation$annotation != "Distal Intergenic"]
unique(k27.consensus.annotation$annotation)
length(target.genes.k27.consensus)
write(x = target.genes.k27.consensus,file = "chipseq_results/h3k27me3/k27_target_genes_consensus.txt") 


```

